173 create geteventvolunteersbyorganization server function
hack4impact-utk/compassion-ministries pull request #179
Opened 2024-03-03 18:20 UTC by Frank-D-stein

# Description
returns all event volunteer responses who have attended an event by an organization

## Relevant issue(s)
- #173 

## Questions
Was I supposed to use EventVolunteerResponse or VolunterrEventResponse? 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have assigned reviewers to this PR

# Test code
```
import { getEventVolunteersByOrganization } from '@/server/actions/Volunteer';
import { EventVolunteerResponse } from '@/types/dataModel/eventVolunteer';

export default async function Home() {
  const eventVolunteers = await getEventVolunteersByOrganization(
    '65da9486c8488f16e6bf6116'
  );

  return (
    <div>
      <h1>Home page</h1>
      <h2>Event Volunteers:</h2>
      <ul>
        {eventVolunteers.map((volunteer: EventVolunteerResponse) => (
          <li key={volunteer._id}>
            <p>
              Name: {volunteer.volunteer.firstName}{' '}
              {volunteer.volunteer.lastName}
            </p>
          </li>
        ))}
      </ul>
    </div>
  );
}
```

2024-03-04 22:05 UTC, andlrutt requested changes
It's functional, but change all occurrences of `EventVolunteer` in comments, var names, etc. to `volunteerEvent`

2024-03-04 22:05 UTC, andlrutt commented on src/server/actions/Volunteer.ts
Just as is done on line 20 of this file with `OrganizationSchema`, import and declare `EventSchema`. If the server hasn't hit the events collection directly before in its current runtime, the schema will not be defined and mongoose will freak out. Importing and declaring it ensures that the code that defines the schema is run

2024-03-04 22:05 UTC, andlrutt commented
> It's functional, but change all occurrences of `EventVolunteer` in comments, var names, etc. to `volunteerEvent`

Also fix merge conflicts :)

2024-03-04 23:43 UTC, Frank-D-stein commented on src/server/actions/Volunteer.ts
Ahh that was what was causing the issue. I was working on fixing that but I ran out of time. Thank you

2024-03-05 00:36 UTC, andlrutt approved these changes
Good stuff!

2024-03-05 02:24 UTC, merged