added api and server functions to update a volunteer
hack4impact-utk/compassion-ministries pull request #42
Opened 2023-11-06 18:28 UTC by dylanbl

# Description
These changes add an API route that is used to update an existing Volunteer in the database. The corresponding server function for this feature was also created. 

## Relevant issue(s)
- [Issue #10](https://github.com/hack4impact-utk/compassion-ministries/issues/10)

## Questions
The code was tested by sending requests to the endpoint using an HTTP client similar to Postman. However more robust testing would be possible if there was test data in the database. Would it be possible to add some garbage volunteers and organizations to the DB for testing? 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have assigned reviewers to this PR

2023-11-07 05:29 UTC, andlrutt commented
no need to add the PR to the project, it clutters up the board a bit., just make sure it is linked to the github issue

2023-11-07 05:46 UTC, andlrutt requested changes

2023-11-16 00:02 UTC, zaviermiller requested changes

2023-11-16 00:02 UTC, zaviermiller commented on src/app/api/volunteers/[volunteerId]/route.ts
> +    return NextResponse.json(
this will just be a 400 error i believe, this means that the `volunteerRequest` is not in the correct shape

2023-11-16 16:05 UTC, zaviermiller submitted a review, later dismissed

2023-12-04 18:17 UTC, zaviermiller approved these changes
looks good, fix merge conflict and lmk when to re-review

2024-01-29 23:24 UTC, zaviermiller commented on src/app/api/volunteers/[volunteerId]/route.ts
>      return NextResponse.json(
add a new function for PUT instead of editing the GET function

2024-01-29 23:25 UTC, zaviermiller commented on src/app/api/volunteers/[volunteerId]/route.ts
> +      { status: 400 }
404

2024-01-29 23:27 UTC, zaviermiller commented on src/app/api/volunteers/[volunteerId]/route.ts
> +  const responseValidation = zVolunteerResponse.safeParse(updatedVolunteer);
unneeded

2024-01-29 23:27 UTC, zaviermiller commented on src/app/api/volunteers/[volunteerId]/route.ts
> +    return new NextResponse(undefined, { status: 204 });
return newly update volunteer

2024-01-29 23:27 UTC, zaviermiller commented on src/app/api/volunteers/[volunteerId]/route.ts
> +    return new NextResponse(undefined, { status: 204 });
200 code

2024-01-29 23:29 UTC, zaviermiller commented on src/types/dataModel/volunteer.ts
> +  role: zVerifiedRole,
add `lastUpdatedAt`

2024-02-09 23:45 UTC, closed without merging